
services:
  mongo-db:
    image: mongo:6.0.6
    restart: always
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
